### ISSUE TITLE
Toml sub-section quotes

### ISSUE THREAD

**Issue by Calytic** [dezhidki/Tommy#14]
Test Code
```csharp
TomlTable expectedNode = new TomlTable
{
    ["section"] = new TomlTable
    {
        ["sub.section"] = new TomlTable
        {
            ["foo"] = "foo",
            ["bar"] = "bar"
        }
    }
};

using (var sw = new StringWriter())
{
    expectedNode.WriteTo(sw);

    string result = sw.ToString();
}
```

Expected Result:
```toml
[section."sub.section"]
foo = "foo"
bar = "bar"
```

Actual Result:
```toml
[section.sub.section]
foo = "foo"
bar = "bar"
```

Additional notes:
1. This problem really only happens if a `.` dot exists in the key.
2. Deserialization works fine if the quotes are supplied in the section.  Only serialization has a problem.
