### ISSUE TITLE
Generated TOML file contains unwanted hashtags between every line

### ISSUE THREAD

**Issue by SteliosLL** [dezhidki/Tommy#19]
When i edit a TOML file and then write it back to the disk, for some reason it has hashtags between every line of a setting. I used the code from the README.MD to write the file.
For example this is how it should be:
```toml
# Help & Documentation: blablabalba
# IMPORTANT: blablabalba

[General]
AuthKey = ''
Debug = false
Description = 'BeamMP Default Description'
Map = '/levels/gridmap/info.json'
MaxCars = 2
MaxPlayers = 10
Name = 'BeamMP Server'
Port = 30814
Private = false
ResourceFolder = 'Resources'
```

This is how it is saved:

```toml
# Help & Documentation: blablabalba
# IMPORTANT: blablabalba

# 
[General]
# 
AuthKey = ''
# 
Debug = false
# 
Description = 'BeamMP Default Description'
# 
Map = '/levels/gridmap/info.json'
# 
MaxCars = 1
# 
MaxPlayers = 10
# 
Name = 'BeamMP New Server'
Port = 10
# 
Private = true
# 
ResourceFolder = 'Resources'
```
