### ISSUE TITLE
When saving an edited TOML file the last line is repeated to the next line corrupted

### ISSUE THREAD

**Issue by SteliosLL** [dezhidki/Tommy#20]
When i save an edited TOML file the last line is repeated to the next line and its corrupted. It does not always happen though. Sometimes it just creates a new empty line at the end for no reason.
This is how the TOML file should look like:

```toml
# Help & Documentation: blablablabla
# IMPORTANT: blablablabla
[General]
AuthKey = ""
Debug = false
Description = "Test server"
Map = "/levels/Desert_Flats/info.json"
MaxCars = 4
MaxPlayers = 2
Name = "BeamMP Server"
Port = 30814
Private = true
ResourceFolder = 'Resources'
```

This is how it sometimes looks like after writing stuff into it:

```toml
# Help & Documentation: blablablabla
# IMPORTANT: blablablabla
[General]
AuthKey = ""
Debug = false
Description = "Test server"
Map = "/levels/Desert_Flats/info.json"
MaxCars = 4
MaxPlayers = 2
Name = "SECOND BeamMP Server"
Port = 30814
Private = true
ResourceFolder = 'Resources'
   'Resources'  <-- HERE IS THE CORRUPTED LINE. Sometimes it can be rces' or es etc. Its always a piece of text from the last line.
EMTPY LINE HERE <--here is a random emtpy line
```
