### ISSUE TITLE
Tables that are not loaded inline as write inline

### ISSUE THREAD

**Issue by HUD-Software** [dezhidki/Tommy#40]
Considering a toml file like this that is valid:
``` toml
[package]
authors = [ "me", "I", "myself" ]
name = "proj"
version = "0.0.1"

[profile.debug]
sanitizer = true
coverage = true

[profile.release]
sanitizer = false
coverage = false

[profile.debug-opt]
```
 When it loaded and save, the toml is broken.
The example code :
```C#
using Tommy;

TomlTable table;

using(StreamReader reader = File.OpenText("file.toml"))
{
    table = TOML.Parse(reader);
}

using (var file = File.OpenWrite("save.toml"))
{
    using StreamWriter sw = new(file);
    table.WriteTo(sw);
}
```

The resulting toml file is not correct:
```toml
[package]
authors = [ "me", "I", "myself" ]
name = "proj"
version = "0.0.1"
profile = { debug = { sanitizer = true, coverage = true }, release = { sanitizer = false, coverage = false }, debug-opt = {} }
```

Table that are not inline in original, should not be inlined when writing it.
